version: '3.1'

services:

  db:
    container_name: mysql
    image: arm64v8/mysql:oracle
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./dbscripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: robosatsob
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev


  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
