torProxyUrl: "socks5://localhost"
torProxyPort: "9150"
nostrPrivkey: ""
nostrRelays: ""
robosatsOnionUrl: "http://robosats6tkf3eva7x2voqso3a5wcorsnw34jveyxfqi2fu7oyheasid.onion"
robosatsReferralUrl: ""
dbUrl: ""
dbTable: ""
dbUsername: ""
dbPassword: ""
